### ISSUE TITLE
How to viz the learned sparse regional attention?

### ISSUE THREAD

**Issue by maudzung** [TuSimple/SST#19]
Dear authors,

Thanks for your interesting paper.
Can you please share with us the source code that uses for the visualization of the learned sparse regional attention? I'd like to reproduce `Fig. 5` in your paper.
Thank you so much!

**Comment by Abyssaledge** [comment]
Thanks for using SST.
I'm sorry that we can not provide you with our visualization code right now because the viz code is quite dirty and incompatible with the current codebase.
Basically, we first save the attention weights of the last block and some related position information (e.g., voxel coordinates, window ID). Then we randomly pick queries in foreground objects and paint the point cloud with the corresponding attention weights in Open3D.

**Comment by maudzung** [comment]
Thank you so much! 👍

**Comment by yinheyanxian** [comment]
> Thank you so much! 👍

Hello, have you realized the visualization of the learned sparse regional attention? I also want to draw a picture like Figure 5.
