### ISSUE TITLE
About reflectance information.

### ISSUE THREAD

**Issue by seonhoon1002** [TuSimple/SST#27]
Hello, I have a question on preprocess.

I wonder why you didn't use the reflectance information, which is used in original mmdetection3D

Is it benefit to improve the performance?

**Comment by Abyssaledge** [comment]
We do not use intensity and elongation in Waymo because theirs numerical value might be extremely large occasionally.
I recommend users to apply tanh to intensity and elongation to normalize the value to [-1, 1] before passing them into model, which attains better performances than the  xyz-only input.

**Comment by seonhoon1002** [comment]
Thank you for your reply
