### ISSUE TITLE
question about position embedding on query, key, value

### ISSUE THREAD

**Issue by seonhoon1002** [TuSimple/SST#30]
Hello, I have a question about position embedding on query, key, value

In your paper, F'=MSA(LN(F),PE(L))+F, so I guessed that the position embedding is added to q,k,v samely. 

But in your codes, postion embedding is only added to query and key, not value.

So I wonder why you add position embedding seperately.

**Comment by Abyssaledge** [comment]
In my opinion, using PE in queries and keys is theoretically correct, because the similarity is calculated based on the query and key, then the queries and keys have larger similarities when they are spatially close (with similar PE).
However, I believe it is also right to add PE to values, you could try it.

**Comment by seonhoon1002** [comment]
Thank you for your reply
