### ISSUE TITLE
No voxel belongs to drop_level:2 in shift 0

### ISSUE THREAD

**Issue by chyohoo** [TuSimple/SST#5]
Hi, I start training SST on nuScenese radar data. The following messages keep popping up: 

No voxel belongs to drop_level:2 in shift 0
No voxel belongs to drop_level:1 in shift 0
No voxel belongs to drop_level:2 in shift 0
No voxel belongs to drop_level:1 in shift 0
No voxel belongs to drop_level:2 in shift 0

From my shallow understanding, does this info relates to region batching? Is this Info normal during region batching?

**Comment by Abyssaledge** [comment]
Yes, this is normal information just for debug, which has no influence on the model. It means there are no enough voxels falling into drop_level 2. 
```
drop_info_training ={
    0:{'max_tokens':30, 'drop_range':(0, 30)},
    1:{'max_tokens':60, 'drop_range':(30, 60)},
    2:{'max_tokens':100, 'drop_range':(60, 100000)},
}
```
For example, if the number of voxels in all the regions is less than 60, the drop_level 2 is not used.
To disable this information, you can adjust the numbers in drop_info. For example, you can use the following one:
```
drop_info_training ={
    0:{'max_tokens':10, 'drop_range':(0, 10)},
    1:{'max_tokens':30, 'drop_range':(10, 30)},
    2:{'max_tokens':60, 'drop_range':(30, 100000)},
}
``` 
But you should be careful when use small number, because heavy dropping will decrease performances.
Or it's also ok if you just comment that `print` line without the modifications above.
